apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: { app: hello-world }
  template:
    metadata:
      labels: { app: hello-world }
    spec:
      topologySpreadConstraints:      # spread pods across nodes
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels: { app: hello-world }
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports: [{ containerPort: 5000 }]
          resources: {{- toYaml .Values.resources | nindent 12 }}